# Generated by Django 6.1.1 on 2026-09-21 08:02

import couples.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=couples.models.generate_invite_code, max_length=12, unique=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('next_meetup', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('partner_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_started', to=settings.AUTH_USER_MODEL)),
                ('partner_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
