# Generated by Django 6.1.1 on 2026-09-21 08:02

import django.db.models.deletion
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.models.strip_upload_path)),
                ('layout', models.CharField(choices=[('strip', 'Classic strip'), ('grid', '2×2 grid')], default='strip', max_length=8)),
                ('caption', models.CharField(blank=True, max_length=80)),
                ('love_note', models.TextField(blank=True, max_length=1000)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strips', to='couples.couple')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strip', to='booth.boothsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
