# Generated by Django 6.1.1 on 2026-09-21 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0001_initial'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photostrip',
            name='owner',
            field=models.ForeignKey(help_text='Who started the session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_strips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photostrip',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strips', to='couples.couple'),
        ),
    ]
