# Generated by Django 6.1.1 on 2026-09-21 08:02

import booth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for both partners'), ('capturing', 'Taking photos'), ('processing', 'Developing strip'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('polaroid', 'Polaroid'), ('film', 'Film'), ('pastel', 'Pastel Hearts')], default='classic', max_length=12)),
                ('photo_filter', models.CharField(choices=[('none', 'Natural'), ('bw', 'Black & White'), ('sepia', 'Sepia'), ('warm', 'Warm')], default='none', max_length=12)),
                ('layout', models.CharField(choices=[('strip', 'Classic strip'), ('grid', '2×2 grid')], default='strip', max_length=8)),
                ('caption', models.CharField(blank=True, max_length=80)),
                ('shots', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='couples.couple')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to=booth.models.frame_upload_path)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='booth.boothsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('session', 'user', 'index'), name='unique_frame_slot')],
            },
        ),
    ]
