# Generated by Django 6.1.1 on 2026-09-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothsession',
            name='mode',
            field=models.CharField(choices=[('duo', 'Together'), ('solo', 'Solo')], default='duo', max_length=4),
        ),
        migrations.AlterField(
            model_name='boothsession',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='couples.couple'),
        ),
    ]
